import InternationalPhoneInput from "@/src/components/InternationalPhoneInput";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Button, TextInput } from "react-native-paper";
import { api } from "../../../src/api/client";
import { colors, spacing } from "../../../src/theme";
export default function MaintenancePropertyInvitationScreen(){const {token}=useLocalSearchParams<{token?:string}>();const[invite,setInvite]=useState<any>(null);const[f,setF]=useState({firstName:"",lastName:"",password:"",phone:"",businessName:"",tradeType:"",registrationNumber:"",insuranceExpiry:""});const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));useEffect(()=>{if(!token)return;api.get(`/property-workflows/maintenance-invitations/${token}`).then(r=>{setInvite(r.data);setF(x=>({...x,firstName:r.data.firstName||"",lastName:r.data.lastName||"",tradeType:r.data.tradeType||""}))}).catch(e=>setMessage(e?.response?.data?.message||"Invitation could not be loaded."));},[token]);const submit=async()=>{if(!token)return;setLoading(true);try{const r=await api.post("/property-workflows/maintenance-invitations/complete",{token,...f,insuranceExpiry:f.insuranceExpiry||undefined});setMessage(r.data.message);setTimeout(()=>router.replace("/auth/maintenance/login" as never),900);}catch(e:any){setMessage(e?.response?.data?.message||"Registration failed.")}finally{setLoading(false)}};return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.card}><Text style={s.title}>Maintenance provider invitation</Text>{invite?<Text style={s.sub}>{invite.property.addressLine1}, {invite.property.townCity} · invited by {invite.invitedByRole.replaceAll("_"," ")}</Text>:null}{[["First name","firstName"],["Last name","lastName"]].map(([l,k])=><TextInput key={k} label={l} value={(f as any)[k]} onChangeText={v=>set(k,v)} style={s.input}/>)}<InternationalPhoneInput label="Phone" value={f.phone} onChangeText={v=>set("phone",v)} style={s.input}/>{[["Business name","businessName"],["Trade / speciality","tradeType"],["Registration number","registrationNumber"],["Insurance expiry (YYYY-MM-DD)","insuranceExpiry"],["Password / existing TenureEx password","password"]].map(([l,k])=><TextInput key={k} label={l} value={(f as any)[k]} onChangeText={v=>set(k,v)} secureTextEntry={k==="password"} style={s.input}/>)}<Button mode="contained" loading={loading} disabled={!invite||f.password.length<8||!f.firstName.trim()||!f.lastName.trim()} onPress={submit}>Complete registration</Button>{message?<Text style={s.message}>{message}</Text>:null}</View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,alignItems:"center"},card:{width:"100%",maxWidth:700,backgroundColor:colors.white,padding:24,borderRadius:18,gap:12},title:{fontSize:26,fontWeight:"900",color:colors.textPrimary},sub:{color:colors.textSecondary},input:{backgroundColor:colors.white},message:{color:colors.primary,fontWeight:"700"}})
