import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import * as argon2 from "argon2";
import { randomBytes } from "crypto";
import type { AuthenticatedUser } from "../auth/decorators/current-user.decorator";
import { PrismaService } from "../database/prisma.service";
import { UserStatus, UserType } from "../generated/prisma/enums";
import { MailService } from "../mail/mail.service";

@Injectable()
export class CouncilInspectionsService {
  constructor(private readonly db: PrismaService, private readonly mail: MailService) {}
  private clean(v: unknown) { return typeof v === "string" ? v.trim() : ""; }
  private async event(inspectionId: string, actorUserId: string, type: string, title: string, message: string) {
    await (this.db as any).councilInspectionEvent.create({ data: { inspectionId, actorUserId, type, title, message } });
  }
  private async notify(recipientUserId: string | null | undefined, type: string, title: string, message: string, entityId?: string) {
    if (!recipientUserId) return;
    await (this.db as any).notification.create({ data: { recipientUserId, type, title, message, entityType: "COUNCIL_INSPECTION", entityId: entityId || null } });
  }
  async inviteInspector(adminUserId: string, body: any) {
    const email=this.clean(body.email).toLowerCase(), firstName=this.clean(body.firstName), lastName=this.clean(body.lastName), councilName=this.clean(body.councilName);
    if (!email || !firstName || !lastName || !councilName) throw new BadRequestException("First name, last name, council name and email are required.");
    const existing=await this.db.user.findUnique({where:{email}}); if(existing) throw new BadRequestException("A TenureEx account already exists for this email.");
    await (this.db as any).councilInvitation.updateMany({where:{email,status:"PENDING"},data:{status:"REVOKED"}});
    const token=randomBytes(32).toString("hex"), tokenHash=await argon2.hash(token), expiresAt=new Date(Date.now()+7*24*60*60*1000);
    const invitation=await (this.db as any).councilInvitation.create({data:{email,firstName,lastName,councilName,department:this.clean(body.department)||null,jobTitle:this.clean(body.jobTitle)||null,employeeId:this.clean(body.employeeId)||null,tokenHash,invitedByUserId:adminUserId,expiresAt}});
    await this.mail.sendCouncilInspectorInvitation({email,firstName,councilName,invitationToken:token});
    return {message:"Council Inspector invitation sent.", invitation:{...invitation,tokenHash:undefined}};
  }
  async listInvitations(){ return (this.db as any).councilInvitation.findMany({orderBy:{createdAt:"desc"},select:{id:true,email:true,firstName:true,lastName:true,councilName:true,department:true,jobTitle:true,employeeId:true,status:true,expiresAt:true,acceptedAt:true,createdAt:true}}); }
  async listInspectors(){ return this.db.user.findMany({where:{userType:UserType.COUNCIL_INSPECTOR},orderBy:{createdAt:"desc"},select:{id:true,firstName:true,lastName:true,email:true,phone:true,status:true,emailVerified:true,lastLoginAt:true,createdAt:true,councilProfile:true}}); }
  async updateInspectorStatus(id:string,status:string){ if(status !== UserStatus.ACTIVE && status !== UserStatus.SUSPENDED && status !== UserStatus.DISABLED) throw new BadRequestException("Invalid inspector status."); return this.db.user.update({where:{id},data:{status:status as UserStatus,suspendedAt:status===UserStatus.SUSPENDED?new Date():null,disabledAt:status===UserStatus.DISABLED?new Date():null}}); }
  private async invitationFromToken(token:string){ const pending=await (this.db as any).councilInvitation.findMany({where:{status:"PENDING",expiresAt:{gt:new Date()}}}); for(const item of pending){ if(await argon2.verify(item.tokenHash,token).catch(()=>false)) return item; } throw new NotFoundException("Invitation is invalid or has expired."); }
  async getInvitation(token:string){ const i=await this.invitationFromToken(token); return {id:i.id,email:i.email,firstName:i.firstName,lastName:i.lastName,councilName:i.councilName,department:i.department,jobTitle:i.jobTitle,employeeId:i.employeeId,expiresAt:i.expiresAt}; }
  async acceptInvitation(token:string,body:any){ const i=await this.invitationFromToken(token); const password=this.clean(body.password),phone=this.clean(body.phone); if(password.length<8) throw new BadRequestException("Password must contain at least 8 characters."); const passwordHash=await argon2.hash(password); const result=await this.db.$transaction(async (tx: any)=>{ const user=await tx.user.create({data:{firstName:i.firstName,lastName:i.lastName,email:i.email,phone:phone||null,passwordHash,userType:UserType.COUNCIL_INSPECTOR,status:UserStatus.ACTIVE,emailVerified:true,activatedAt:new Date(),councilProfile:{create:{councilName:i.councilName,department:i.department,employeeId:i.employeeId,jobTitle:i.jobTitle}}}}); await tx.councilInvitation.update({where:{id:i.id},data:{status:"ACCEPTED",acceptedAt:new Date()}}); return user; }); return {message:"Council Inspector account activated.",userId:result.id}; }
  async directory(user:AuthenticatedUser){ if(user.userType===UserType.MAINTENANCE_PROVIDER) throw new ForbiddenException(); return this.db.user.findMany({where:{userType:UserType.COUNCIL_INSPECTOR,status:UserStatus.ACTIVE,emailVerified:true},orderBy:[{firstName:"asc"},{lastName:"asc"}],select:{id:true,firstName:true,lastName:true,email:true,phone:true,councilProfile:true}}); }
  private async propertyWithOwner(propertyId:string){ const p=await this.db.property.findUnique({where:{id:propertyId},include:{landlordProfile:{include:{agency:true,user:true}}}}); if(!p) throw new NotFoundException("Property not found."); return p; }
  private async canAccessProperty(user:AuthenticatedUser,propertyId:string){ if(user.userType===UserType.TENUREEX_ADMIN||user.userType===UserType.TENUREEX_STAFF) return true; const p=await this.propertyWithOwner(propertyId); if(user.userType===UserType.LANDLORD) return p.landlordProfile.userId===user.sub; if(user.userType===UserType.TENANT) return !!await this.db.propertyTenant.findFirst({where:{propertyId,tenantUserId:user.sub,status:"ACTIVE"}}); if(user.userType===UserType.ESTATE_AGENT){ if(!p.landlordProfile.agencyId) return false; return !!await this.db.agencyUser.findFirst({where:{agencyId:p.landlordProfile.agencyId,userId:user.sub}}); } return false; }
  async accessibleProperties(user:AuthenticatedUser){ if(user.userType===UserType.TENANT){ const links=await this.db.propertyTenant.findMany({where:{tenantUserId:user.sub,status:"ACTIVE"}}); return this.db.property.findMany({where:{id:{in:links.map(x=>x.propertyId)}},select:{id:true,addressLine1:true,townCity:true,postcode:true,councilName:true}}); } if(user.userType===UserType.LANDLORD){ const lp=await this.db.landlordProfile.findUnique({where:{userId:user.sub}}); return lp?this.db.property.findMany({where:{landlordProfileId:lp.id},select:{id:true,addressLine1:true,townCity:true,postcode:true,councilName:true}}):[]; } if(user.userType===UserType.ESTATE_AGENT){ const memberships=await this.db.agencyUser.findMany({where:{userId:user.sub}}); const landlords=await this.db.landlordProfile.findMany({where:{agencyId:{in:memberships.map(x=>x.agencyId)}}}); return this.db.property.findMany({where:{landlordProfileId:{in:landlords.map(x=>x.id)}},select:{id:true,addressLine1:true,townCity:true,postcode:true,councilName:true}}); } return []; }
  async createCase(user:AuthenticatedUser,body:any){ if(user.userType !== UserType.TENANT && user.userType !== UserType.LANDLORD && user.userType !== UserType.ESTATE_AGENT) throw new ForbiddenException("This account cannot request a council inspection."); const propertyId=this.clean(body.propertyId); if(!await this.canAccessProperty(user,propertyId)) throw new ForbiddenException("You cannot request an inspection for this property."); const inspectorId=this.clean(body.inspectorUserId); const inspector=await this.db.user.findFirst({where:{id:inspectorId,userType:UserType.COUNCIL_INSPECTOR,status:UserStatus.ACTIVE}}); if(!inspector) throw new BadRequestException("Please select an active Council Inspector."); const title=this.clean(body.title),description=this.clean(body.description),category=this.clean(body.category)||"HOUSING_CONDITION"; if(!title||!description) throw new BadRequestException("Title and description are required."); const c=await (this.db as any).councilInspectionCase.create({data:{propertyId,requestedByUserId:user.sub,inspectorUserId:inspector.id,title,description,category,priority:this.clean(body.priority)||"NORMAL",accessNotes:this.clean(body.accessNotes)||null}}); await this.event(c.id,user.sub,"CREATED","Inspection requested",title); await this.notify(inspector.id,"COUNCIL_INSPECTION_REQUEST","New inspection request",title,c.id); return this.getCase(user,c.id); }
  private async canAccessCase(user:AuthenticatedUser,c:any){ if(user.userType === UserType.TENUREEX_ADMIN || user.userType === UserType.TENUREEX_STAFF) return true; if(user.userType===UserType.COUNCIL_INSPECTOR) return c.inspectorUserId===user.sub; if(c.requestedByUserId===user.sub) return true; return this.canAccessProperty(user,c.propertyId); }
  async listCases(user:AuthenticatedUser,status?:string){ let where:any={}; if(status&&status!=="ALL") where.status=status; if(user.userType===UserType.COUNCIL_INSPECTOR) where.inspectorUserId=user.sub; else if(user.userType===UserType.TENANT) where= {...where, OR:[{requestedByUserId:user.sub},{propertyId:{in:(await this.accessibleProperties(user)).map((x:any)=>x.id)}}]}; else if(user.userType===UserType.LANDLORD||user.userType===UserType.ESTATE_AGENT) where.propertyId={in:(await this.accessibleProperties(user)).map((x:any)=>x.id)}; else if(user.userType !== UserType.TENUREEX_ADMIN && user.userType !== UserType.TENUREEX_STAFF) throw new ForbiddenException(); const cases=await (this.db as any).councilInspectionCase.findMany({where,orderBy:{createdAt:"desc"}}); return this.enrichCases(cases); }
  private async enrichCases(cases:any[]){ const propertyIds=[...new Set(cases.map(x=>x.propertyId))], userIds=[...new Set(cases.flatMap(x=>[x.requestedByUserId,x.inspectorUserId]).filter(Boolean))]; const [props,users]=await Promise.all([this.db.property.findMany({where:{id:{in:propertyIds}},select:{id:true,addressLine1:true,townCity:true,postcode:true,councilName:true}}),this.db.user.findMany({where:{id:{in:userIds}},select:{id:true,firstName:true,lastName:true,email:true,phone:true,councilProfile:true}})]); return cases.map(c=>({...c,property:props.find(p=>p.id===c.propertyId)||null,requester:users.find(u=>u.id===c.requestedByUserId)||null,inspector:users.find(u=>u.id===c.inspectorUserId)||null})); }
  async getCase(user:AuthenticatedUser,id:string){ const c=await (this.db as any).councilInspectionCase.findUnique({where:{id}}); if(!c) throw new NotFoundException("Inspection case not found."); if(!await this.canAccessCase(user,c)) throw new ForbiddenException(); const [enriched]=await this.enrichCases([c]); const [findings,actions,evidence,events]=await Promise.all([(this.db as any).councilInspectionFinding.findMany({where:{inspectionId:id},orderBy:{createdAt:"asc"}}),(this.db as any).councilInspectionAction.findMany({where:{inspectionId:id},orderBy:{createdAt:"asc"}}),(this.db as any).councilInspectionEvidence.findMany({where:{inspectionId:id},orderBy:{createdAt:"desc"}}),(this.db as any).councilInspectionEvent.findMany({where:{inspectionId:id},orderBy:{createdAt:"desc"}})]); return {...enriched,findings,actions,evidence,events}; }
  private async inspectorCase(user:AuthenticatedUser,id:string){ if(user.userType!==UserType.COUNCIL_INSPECTOR) throw new ForbiddenException("Council Inspector access required."); const c=await (this.db as any).councilInspectionCase.findUnique({where:{id}}); if(!c||c.inspectorUserId!==user.sub) throw new ForbiddenException("This inspection is not assigned to you."); return c; }
  async acceptCase(user:AuthenticatedUser,id:string){ await this.inspectorCase(user,id); const c=await (this.db as any).councilInspectionCase.update({where:{id},data:{status:"ACCEPTED",acceptedAt:new Date(),declinedAt:null}}); await this.event(id,user.sub,"ACCEPTED","Inspection accepted","The Council Inspector accepted the inspection request."); await this.notify(c.requestedByUserId,"COUNCIL_INSPECTION_ACCEPTED","Inspection request accepted",c.title,id); return this.getCase(user,id); }
  async declineCase(user:AuthenticatedUser,id:string,reason?:string){ await this.inspectorCase(user,id); const c=await (this.db as any).councilInspectionCase.update({where:{id},data:{status:"DECLINED",declinedAt:new Date()}}); await this.event(id,user.sub,"DECLINED","Inspection declined",this.clean(reason)||"The inspection request was declined."); await this.notify(c.requestedByUserId,"COUNCIL_INSPECTION_DECLINED","Inspection request declined",this.clean(reason)||c.title,id); return this.getCase(user,id); }
  async scheduleCase(user:AuthenticatedUser,id:string,body:any){ await this.inspectorCase(user,id); const start=new Date(body.startAt),end=new Date(body.endAt); if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start) throw new BadRequestException("Valid inspection start and end times are required."); const c=await (this.db as any).councilInspectionCase.update({where:{id},data:{scheduledStart:start,scheduledEnd:end,status:"SCHEDULED"}}); await this.event(id,user.sub,"SCHEDULED","Inspection scheduled",`Inspection scheduled for ${start.toISOString()}.`); await this.notify(c.requestedByUserId,"COUNCIL_INSPECTION_SCHEDULED","Inspection scheduled",c.title,id); return this.getCase(user,id); }
  async updateInspection(user:AuthenticatedUser,id:string,body:any){ await this.inspectorCase(user,id); const data:any={}; if(body.status) data.status=this.clean(body.status); if(body.inspectionNotes!==undefined) data.inspectionNotes=this.clean(body.inspectionNotes)||null; if(body.outcome!==undefined) data.outcome=this.clean(body.outcome)||null; if(data.status==="COMPLETED") data.completedAt=new Date(); const c=await (this.db as any).councilInspectionCase.update({where:{id},data}); await this.event(id,user.sub,"INSPECTION_UPDATED","Inspection updated",data.outcome||data.status||"Inspection details updated."); await this.notify(c.requestedByUserId,"COUNCIL_INSPECTION_UPDATED","Inspection updated",c.title,id); return this.getCase(user,id); }
  async addFinding(user:AuthenticatedUser,id:string,body:any){ await this.inspectorCase(user,id); const description=this.clean(body.description); if(!description) throw new BadRequestException("Finding description is required."); const f=await (this.db as any).councilInspectionFinding.create({data:{inspectionId:id,category:this.clean(body.category)||"Housing condition",hazard:this.clean(body.hazard)||null,severity:this.clean(body.severity)||"MINOR",location:this.clean(body.location)||null,description,recommendation:this.clean(body.recommendation)||null,createdByUserId:user.sub}}); await this.event(id,user.sub,"FINDING_ADDED","Inspection finding added",description); return f; }
  async addAction(user:AuthenticatedUser,id:string,body:any){ await this.inspectorCase(user,id); const title=this.clean(body.title),description=this.clean(body.description); if(!title||!description) throw new BadRequestException("Action title and description are required."); const a=await (this.db as any).councilInspectionAction.create({data:{inspectionId:id,findingId:this.clean(body.findingId)||null,title,description,priority:this.clean(body.priority)||"NORMAL",dueAt:body.dueAt?new Date(body.dueAt):null}}); const c=await (this.db as any).councilInspectionCase.update({where:{id},data:{status:"ACTION_REQUIRED"}}); await this.event(id,user.sub,"ACTION_REQUIRED","Required action issued",title); await this.notify(c.requestedByUserId,"COUNCIL_ACTION_REQUIRED","Council action required",title,id); return a; }
  async addEvidence(user:AuthenticatedUser,id:string,body:any){ const c=await (this.db as any).councilInspectionCase.findUnique({where:{id}}); if(!c||!await this.canAccessCase(user,c)) throw new ForbiddenException(); const e=await (this.db as any).councilInspectionEvidence.create({data:{inspectionId:id,actionId:this.clean(body.actionId)||null,uploadedByUserId:user.sub,note:this.clean(body.note)||null,fileName:this.clean(body.fileName)||null,fileUrl:this.clean(body.fileUrl)||null}}); if(e.actionId) await (this.db as any).councilInspectionAction.updateMany({where:{id:e.actionId,inspectionId:id},data:{status:"EVIDENCE_SUBMITTED",completedAt:new Date()}}); await this.event(id,user.sub,"EVIDENCE_SUBMITTED","Evidence submitted",this.clean(body.note)||"Evidence was submitted for review."); if(c.inspectorUserId) await this.notify(c.inspectorUserId,"COUNCIL_EVIDENCE_SUBMITTED","Evidence submitted",c.title,id); return e; }
  async createMaintenanceFromAction(user:AuthenticatedUser,id:string,actionId:string){ const c=await (this.db as any).councilInspectionCase.findUnique({where:{id}}); if(!c||!await this.canAccessCase(user,c)) throw new ForbiddenException(); if(user.userType===UserType.COUNCIL_INSPECTOR) throw new ForbiddenException("Inspectors record required actions; the landlord or Estate Agent creates repair jobs."); const a=await (this.db as any).councilInspectionAction.findFirst({where:{id:actionId,inspectionId:id}}); if(!a) throw new NotFoundException("Required action not found."); if(a.maintenanceRequestId) return {maintenanceRequestId:a.maintenanceRequestId}; const tenancy=await this.db.propertyTenant.findFirst({where:{propertyId:c.propertyId,status:"ACTIVE"},orderBy:{startedAt:"desc"}}); if(!tenancy) throw new BadRequestException("An active tenant is required before a maintenance job can be created."); const profile=await this.db.tenantProfile.findUnique({where:{userId:tenancy.tenantUserId}}); if(!profile) throw new BadRequestException("Tenant profile not found."); const req=await this.db.maintenanceRequest.create({data:{propertyId:c.propertyId,tenantUserId:tenancy.tenantUserId,tenantProfileId:profile.id,title:`Council action: ${a.title}`,description:a.description,category:"COUNCIL_REQUIRED_WORK",priority:a.priority==="URGENT"?"HIGH":"MEDIUM",status:"AWAITING_TENANT_AVAILABILITY",accessPermission:false}}); await (this.db as any).councilInspectionAction.update({where:{id:a.id},data:{maintenanceRequestId:req.id,status:"MAINTENANCE_CREATED"}}); await this.event(id,user.sub,"MAINTENANCE_CREATED","Maintenance job created",a.title); await this.notify(tenancy.tenantUserId,"MAINTENANCE_AVAILABILITY_REQUIRED","Add maintenance availability",`Council-required work has been created for ${a.title}. Add suitable visit times so an approved maintenance provider can accept the job.`,id); return {maintenanceRequestId:req.id}; }
  async verifyAction(user:AuthenticatedUser,id:string,actionId:string){ await this.inspectorCase(user,id); const a=await (this.db as any).councilInspectionAction.update({where:{id:actionId},data:{status:"VERIFIED",verifiedAt:new Date()}}); await this.event(id,user.sub,"ACTION_VERIFIED","Required action verified",a.title); return a; }
  async closeCase(user:AuthenticatedUser,id:string){ await this.inspectorCase(user,id); const open=await (this.db as any).councilInspectionAction.count({where:{inspectionId:id,status:{not:"VERIFIED"}}}); if(open>0) throw new BadRequestException("All required actions must be verified before the case can be closed."); const c=await (this.db as any).councilInspectionCase.update({where:{id},data:{status:"CLOSED",closedAt:new Date()}}); await this.event(id,user.sub,"CLOSED","Inspection case closed","All required actions have been verified."); await this.notify(c.requestedByUserId,"COUNCIL_INSPECTION_CLOSED","Inspection case closed",c.title,id); return this.getCase(user,id); }
}
