import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Linking, StyleSheet, Text, View } from "react-native";
import { Button, Chip } from "react-native-paper";
import { api } from "../../src/api/client";
import ScreenContainer from "../../src/components/ScreenContainer";
import { colors, radius, spacing } from "../../src/theme";

type Provider = any;
export default function AdminMaintenanceProvidersScreen(){
 const [providers,setProviders]=useState<Provider[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/property-workflows/admin/maintenance-providers");setProviders(Array.isArray(r.data)?r.data:[]);setMessage("")}catch(e:any){setMessage(e?.response?.data?.message||"Unable to load maintenance providers.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const review=async(id:string,action:"APPROVE"|"REJECT")=>{try{await api.patch(`/property-workflows/admin/maintenance-providers/${id}/review`,{action});await load()}catch(e:any){setMessage(e?.response?.data?.message||"Unable to review provider.")}};
 const open=(url?:string|null)=>{if(url) void Linking.openURL(api.getUri({url}));};
 return <ScreenContainer scrollable contentStyle={s.page}><View style={s.wrap}><View style={s.head}><View><Text style={s.title}>Maintenance Providers</Text><Text style={s.sub}>Review provider identity, business details and supporting certificates before account activation.</Text></View><View style={s.actions}><Button mode="outlined" onPress={()=>router.push("/admin/dashboard" as never)}>Admin dashboard</Button><Button mode="outlined" icon="refresh" loading={loading} onPress={load}>Refresh</Button></View></View>{message?<Text style={s.message}>{message}</Text>:null}{providers.length?providers.map((p)=><View key={p.id} style={s.card}><View style={s.cardHead}><View style={{flex:1}}><Text style={s.name}>{p.user?.firstName} {p.user?.lastName}</Text><Text style={s.sub}>{p.user?.email} · {p.user?.phone||"No phone"}</Text></View><Chip icon={p.approved?"check-decagram":"clock-outline"}>{p.approved?"Admin approved":p.user?.status==="REJECTED"?"Rejected":"Pending review"}</Chip></View><View style={s.grid}><Info label="Provider type" value={p.providerType?.replaceAll("_"," ")}/><Info label="Trade / speciality" value={p.tradeType}/><Info label="Service area" value={p.serviceArea}/><Info label="Business name" value={p.businessName}/><Info label="Company number" value={p.companyNumber}/><Info label="Registration number" value={p.registrationNumber}/><Info label="Business address" value={p.businessAddress}/><Info label="Insurance expiry" value={p.insuranceExpiry?new Date(p.insuranceExpiry).toLocaleDateString("en-GB"):null}/></View><View style={s.docs}><Text style={s.section}>Verification documents</Text>{p.idDocumentUrl?<Button mode="outlined" icon="card-account-details" onPress={()=>open(p.idDocumentUrl)}>View {p.idDocumentName||"ID document"}</Button>:<Text style={s.warning}>No ID document supplied</Text>}{(p.certificateUrls||[]).map((url:string,i:number)=><Button key={url} mode="text" icon="certificate-outline" onPress={()=>open(url)}>View {p.certificateNames?.[i]||`Certificate ${i+1}`}</Button>)}</View>{!p.approved?<View style={s.actions}><Button mode="contained" icon="check" onPress={()=>review(p.id,"APPROVE")}>Approve provider</Button><Button mode="outlined" textColor={colors.error} icon="close" onPress={()=>review(p.id,"REJECT")}>Reject</Button></View>:null}</View>):!loading?<View style={s.empty}><MaterialCommunityIcons name="tools" size={34} color={colors.textMuted}/><Text style={s.sub}>No maintenance providers have registered yet.</Text></View>:null}</View></ScreenContainer>
}
function Info({label,value}:{label:string;value?:string|null}){return <View style={s.info}><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value||"—"}</Text></View>}
const s=StyleSheet.create({page:{padding:spacing.xl},wrap:{maxWidth:1180,width:"100%",alignSelf:"center",gap:18},head:{flexDirection:"row",justifyContent:"space-between",gap:12,flexWrap:"wrap"},title:{fontSize:28,fontWeight:"900",color:colors.textPrimary},sub:{color:colors.textSecondary,marginTop:4},actions:{flexDirection:"row",gap:8,flexWrap:"wrap"},message:{padding:12,borderRadius:radius.md,backgroundColor:colors.primaryLight,color:colors.primary,fontWeight:"700"},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:20,gap:16},cardHead:{flexDirection:"row",alignItems:"center",gap:12},name:{fontSize:19,fontWeight:"900",color:colors.textPrimary},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},info:{minWidth:210,flexGrow:1,padding:12,borderRadius:12,backgroundColor:colors.background},infoLabel:{fontSize:11,fontWeight:"800",color:colors.textMuted,textTransform:"uppercase"},infoValue:{marginTop:4,fontWeight:"700",color:colors.textPrimary},docs:{gap:8},section:{fontWeight:"900",color:colors.textPrimary},warning:{color:colors.error,fontWeight:"700"},empty:{padding:40,alignItems:"center",gap:10}});
