import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Button, Dialog, Portal, TextInput } from "react-native-paper";
import { api } from "../api/client";
import { colors, radius } from "../theme";

type Inspector = { id:string; firstName:string; lastName:string; email:string; phone?:string|null; councilProfile?:{ councilName:string; department?:string|null; jobTitle?:string|null }|null };
type Property = { id:string; addressLine1:string; townCity:string; postcode:string; councilName?:string|null };
type CaseRow = { id:string; title:string; category:string; priority:string; status:string; createdAt:string; scheduledStart?:string|null; property?:Property|null; inspector?:Inspector|null };

export default function CouncilInspectionHub({ portal }: { portal:"tenant"|"landlord"|"agent" }) {
  const [inspectors,setInspectors]=useState<Inspector[]>([]); const [properties,setProperties]=useState<Property[]>([]); const [cases,setCases]=useState<CaseRow[]>([]);
  const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  const [propertyId,setPropertyId]=useState(""); const [inspectorId,setInspectorId]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [category,setCategory]=useState("Housing condition"); const [priority,setPriority]=useState("NORMAL"); const [accessNotes,setAccessNotes]=useState("");
  const load=async()=>{ setLoading(true); try { const [d,p,c]=await Promise.all([api.get("/council-inspections/directory"),api.get("/council-inspections/properties"),api.get("/council-inspections/cases")]); setInspectors(Array.isArray(d.data)?d.data:[]); setProperties(Array.isArray(p.data)?p.data:[]); setCases(Array.isArray(c.data)?c.data:[]); } catch(e:any){setMessage(e?.response?.data?.message||"Unable to load Council & Inspections.");} finally {setLoading(false);} };
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase(); return !q?cases:cases.filter(x=>`${x.title} ${x.status} ${x.property?.addressLine1||""} ${x.inspector?.firstName||""} ${x.inspector?.lastName||""}`.toLowerCase().includes(q))},[cases,search]);
  const submit=async()=>{ if(!propertyId||!inspectorId||!title.trim()||!description.trim()){setMessage("Select a property and inspector, then enter the issue title and description.");return;} setLoading(true); try { await api.post("/council-inspections/cases",{propertyId,inspectorUserId:inspectorId,title,description,category,priority,accessNotes}); setOpen(false); setTitle("");setDescription("");setAccessNotes(""); setMessage("Inspection request sent to the Council Inspector."); await load(); } catch(e:any){setMessage(e?.response?.data?.message||"Unable to create inspection request.");} finally{setLoading(false);} };
  return <View style={s.wrap}>
    <View style={s.heading}><View><Text style={s.title}>Council & Inspections</Text><Text style={s.sub}>Request a housing inspection and follow findings, required work and closure.</Text></View><Button mode="contained" icon="plus" onPress={()=>setOpen(true)}>Request inspection</Button></View>
    {message?<Text style={s.message}>{String(message)}</Text>:null}
    <TextInput mode="outlined" placeholder="Search inspection cases..." value={search} onChangeText={setSearch} left={<TextInput.Icon icon="magnify"/>}/>
    <View style={s.stats}><Stat label="My cases" value={cases.length}/><Stat label="Open" value={cases.filter(x=>!["CLOSED","DECLINED"].includes(x.status)).length}/><Stat label="Inspectors" value={inspectors.length}/></View>
    <Text style={s.section}>Inspection cases</Text>
    {loading && !cases.length?<Text style={s.empty}>Loading...</Text>:filtered.length===0?<Text style={s.empty}>No inspection cases yet.</Text>:filtered.map(item=><Pressable key={item.id} style={s.card} onPress={()=>router.push(`/${portal}/council-inspection-details?inspectionId=${item.id}` as never)}>
      <View style={s.icon}><MaterialCommunityIcons name="clipboard-search-outline" size={22} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.cardSub}>{item.property?[item.property.addressLine1,item.property.postcode].filter(Boolean).join(", "):"Property"}</Text><Text style={s.cardMeta}>{item.inspector?`${item.inspector.firstName} ${item.inspector.lastName} · ${item.inspector.councilProfile?.councilName||"Council Inspector"}`:"Inspector"}</Text></View><View><Text style={s.status}>{item.status.replace(/_/g," ")}</Text><Text style={s.priority}>{item.priority}</Text></View></Pressable>)}
    <Text style={s.section}>Approved Council Inspectors</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{inspectors.map(i=><View key={i.id} style={s.inspector}><MaterialCommunityIcons name="badge-account-outline" size={28} color={colors.primary}/><Text style={s.inspectorName}>{i.firstName} {i.lastName}</Text><Text style={s.cardSub}>{i.councilProfile?.jobTitle||"Council Inspector"}</Text><Text style={s.cardMeta}>{i.councilProfile?.councilName||"Local authority"}</Text></View>)}</ScrollView>
    <Portal><Dialog visible={open} onDismiss={()=>setOpen(false)} style={s.dialog}><Dialog.Title>Request Council inspection</Dialog.Title><Dialog.ScrollArea><ScrollView contentContainerStyle={{paddingVertical:8,gap:12}}>
      <Text style={s.label}>Property</Text>{properties.map(p=><Pressable key={p.id} onPress={()=>setPropertyId(p.id)} style={[s.choice,propertyId===p.id&&s.choiceActive]}><Text style={propertyId===p.id?s.choiceTextActive:s.choiceText}>{p.addressLine1}, {p.postcode}</Text></Pressable>)}
      <Text style={s.label}>Council Inspector</Text>{inspectors.map(i=><Pressable key={i.id} onPress={()=>setInspectorId(i.id)} style={[s.choice,inspectorId===i.id&&s.choiceActive]}><Text style={inspectorId===i.id?s.choiceTextActive:s.choiceText}>{i.firstName} {i.lastName} · {i.councilProfile?.councilName}</Text></Pressable>)}
      <TextInput mode="outlined" label="Issue title" value={title} onChangeText={setTitle}/><TextInput mode="outlined" label="Category" value={category} onChangeText={setCategory}/><TextInput mode="outlined" label="Description" value={description} onChangeText={setDescription} multiline numberOfLines={4}/><TextInput mode="outlined" label="Priority (NORMAL / HIGH / URGENT)" value={priority} onChangeText={setPriority}/><TextInput mode="outlined" label="Access notes" value={accessNotes} onChangeText={setAccessNotes} multiline/>
    </ScrollView></Dialog.ScrollArea><Dialog.Actions><Button onPress={()=>setOpen(false)}>Cancel</Button><Button mode="contained" loading={loading} onPress={submit}>Send request</Button></Dialog.Actions></Dialog></Portal>
  </View>
}
function Stat({label,value}:{label:string;value:number}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.cardSub}>{label}</Text></View>}
const s=StyleSheet.create({wrap:{gap:18},heading:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",gap:12},title:{fontSize:24,fontWeight:"900",color:colors.textPrimary},sub:{marginTop:4,color:colors.textSecondary},message:{padding:12,borderRadius:radius.md,backgroundColor:colors.primaryLight,color:colors.primary,fontWeight:"700"},stats:{flexDirection:"row",flexWrap:"wrap",gap:12},stat:{minWidth:130,padding:16,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.white},statValue:{fontSize:24,fontWeight:"900",color:colors.textPrimary},section:{fontSize:16,fontWeight:"900",color:colors.textPrimary,marginTop:4},empty:{padding:22,color:colors.textMuted,textAlign:"center"},card:{flexDirection:"row",alignItems:"center",gap:12,padding:16,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.white},icon:{width:44,height:44,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:colors.primaryLight},cardTitle:{fontWeight:"900",color:colors.textPrimary},cardSub:{marginTop:3,color:colors.textSecondary,fontSize:12},cardMeta:{marginTop:3,color:colors.textMuted,fontSize:11},status:{fontSize:10,fontWeight:"900",color:colors.primary,textAlign:"right"},priority:{marginTop:4,fontSize:9,color:colors.textMuted,textAlign:"right"},inspector:{width:220,padding:16,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.white},inspectorName:{marginTop:8,fontWeight:"900",color:colors.textPrimary},dialog:{alignSelf:"center",width:"92%",maxWidth:640,maxHeight:"90%"},label:{fontWeight:"900",color:colors.textPrimary},choice:{padding:11,borderWidth:1,borderColor:colors.border,borderRadius:radius.md},choiceActive:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{color:colors.textSecondary},choiceTextActive:{color:colors.white,fontWeight:"800"}});
